config/routes.rb
Rails.application.routes.draw do
  get 'welcome/new'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :welcome_pages

  root 'welcome#new'

end

app/models/welcome_page.rb
class WelcomePage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def new
  end
end

app/controllers/welcome_pages_controller.rb
class WelcomePagesController < ApplicationController
  before_action :set_welcome_page, only: [:show, :edit, :update, :destroy]

  # GET /welcome_pages
  # GET /welcome_pages.json
  def index
    @welcome_pages = WelcomePage.all
  end

  # GET /welcome_pages/1
  # GET /welcome_pages/1.json
  def show
  end

  # GET /welcome_pages/new
  def new
    @welcome_page = WelcomePage.new
  end

  # GET /welcome_pages/1/edit
  def edit
  end

  # POST /welcome_pages
  # POST /welcome_pages.json
  def create
    @welcome_page = WelcomePage.new(welcome_page_params)

    respond_to do |format|
      if @welcome_page.save
        format.html { redirect_to @welcome_page, notice: 'Welcome page was successfully created.' }
        format.json { render :show, status: :created, location: @welcome_page }
      else
        format.html { render :new }
        format.json { render json: @welcome_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcome_pages/1
  # PATCH/PUT /welcome_pages/1.json
  def update
    respond_to do |format|
      if @welcome_page.update(welcome_page_params)
        format.html { redirect_to @welcome_page, notice: 'Welcome page was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome_page }
      else
        format.html { render :edit }
        format.json { render json: @welcome_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcome_pages/1
  # DELETE /welcome_pages/1.json
  def destroy
    @welcome_page.destroy
    respond_to do |format|
      format.html { redirect_to welcome_pages_url, notice: 'Welcome page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome_page
      @welcome_page = WelcomePage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_page_params
      params[:welcome_page]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcome_pages_helper.rb
module WelcomePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/new.html.erb
<html>
<head>
	<title>
		Hamstering Around
	</title>
	<style type="text/css">

	body{

		background: white;
		margin-left: auto;
		margin-right: auto;
		text-align: center;
		padding-left: 0%;
		padding-right: 0%;
		width: 1000px;
		max-width: 1000px;
		min-width: 1000px;
		color: #8C8984;
		font: 100%/1.4 Veranda, Ariel, Helvetica;
		font-size: 50px;
	}

	.smaller{
		font-size: 16px;
	}

	</style>
</head>

<body>
	<p>STOP HAMSTERING ME!!!!!!</p>
</body>
<a>
	<%=image_tag("hamstering.jpg", alt: "Ins")%>
	
</a>

<ul>
	<ul> These instructions have been brought to you by Munchkin of Munchkinland</ul>
</ul>

</body>
</html>

<% provide(:title, "Log in") %>
<ul>Log in</ul>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>
	<ul>
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
  </ul>
    <% end %>

    <ul>New user? <%= link_to "Sign up now!", signup_path %></ul>
  </div>
</div>

<ul>Find me in app/views/welcome/new.html.erb</ul>

app/views/welcome_pages/_form.html.erb
<%= form_for(@welcome_page) do |f| %>
  <% if @welcome_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@welcome_page.errors.count, "error") %> prohibited this welcome_page from being saved:</h2>

      <ul>
      <% @welcome_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcome_pages/edit.html.erb
<h1>Editing welcome_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @welcome_page %> |
<%= link_to 'Back', welcome_pages_path %>

app/views/welcome_pages/index.html.erb
<h1>Listing welcome_pages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @welcome_pages.each do |welcome_page| %>
      <tr>
        <td><%= link_to 'Show', welcome_page %></td>
        <td><%= link_to 'Edit', edit_welcome_page_path(welcome_page) %></td>
        <td><%= link_to 'Destroy', welcome_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Welcome page', new_welcome_page_path %>

app/views/welcome_pages/new.html.erb
<h1>New welcome_page</h1>

<%= render 'form' %>

<%= link_to 'Back', welcome_pages_path %>

app/views/welcome_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_welcome_page_path(@welcome_page) %> |
<%= link_to 'Back', welcome_pages_path %>